server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  application:
    name: edge-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000 #2s
        response-timeout: 5s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      default-filters:
        - SaveSession
        - TokenRelay
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
              requestedTokens: 1
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException
            backoff:
              firstBackoff: 50ms
              maxBackOff: 500ms
              factor: 2
              basedOnPreviousValue: false
      routes:
        - id: ui-service-route
          uri: ${UI_SERVICE_URL:http://localhost:4200}/
          predicates:
            - Path=/,/*,*.html,/*.css,/*.js,/favicon.ico
          filters:
            - StripPrefix=0
        - id: api-service-route
          uri: ${API_SERVICE_URL:http://localhost:9001}/
          predicates:
            - Path=/chat/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                fallbackUri: forward:/api-fallback
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: edge-service
            client-secret: cT5pq7W3XStcuFVQMhjPbRj57Iqxcu4n
            scope: openid, profile, roles
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/chat
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  session:
    redis:
      namespace: chat:edge
    timeout: 10m

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 20
        permitted-number-of-calls-in-half-open-state: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15000
  timelimiter:
    configs:
      default:
        timeout-duration: 5s

logging:
  group:
    circuitbreaker: io.github.resilience4j, org.springframework.cloud.circuitbreaker
  level:
    circuitbreaker: debug

info:
  system: Chat system

management:
  endpoints:
    web:
      exposure:
        include: info, health
  # Configuration probes for Kubernetes probes
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include:
            - readinessState
            - redis
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
